name: Check coding style

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up directories
        run: |
          DELIVERY_DIR='.'
          REPORTS_DIR='.'
          EXPORT_FILE="$REPORTS_DIR/coding-style-reports.log"

          # Remove existing report file
          rm -f "$EXPORT_FILE"

          # Pull the Docker image
          echo "Pulling Docker image..."
          docker pull ghcr.io/epitech/coding-style-checker:latest

          # Run the Docker container to generate reports
          echo "Running Docker container..."
          docker run --rm --security-opt "label:disable" -i -v "$DELIVERY_DIR:/mnt/delivery" -v "$REPORTS_DIR:/mnt/reports" ghcr.io/epitech/coding-style-checker:latest "/mnt/delivery" "/mnt/reports"

          # Check for coding style errors
          if [[ -f "$EXPORT_FILE" ]]; then
            echo "$(wc -l < "$EXPORT_FILE") coding style error(s) reported in $EXPORT_FILE, $(grep -c ": MAJOR:" "$EXPORT_FILE") major, $(grep -c ": MINOR:" "$EXPORT_FILE") minor, $(grep -c ": INFO:" "$EXPORT_FILE") info"
            if [[ $(wc -l < "$EXPORT_FILE") -gt 0 ]]; then
              echo "Coding style errors found."
              cat "$EXPORT_FILE"
              exit 1
            else
              echo "No coding style errors found."
            fi
          else
            echo "No export file found."
          fi
